# configs/base_config.yaml
# --------------------------------------------------
# 这是所有实验的基础配置文件。
# 特定模型的配置文件（如 bigram.yaml）将覆盖这些值。
# --------------------------------------------------

# 系统和路径相关配置
system:
  work_dir: 'out'        # 默认输出目录
  seed: 3407             # 全局随机种子

# 数据加载器配置
data:
  data_dir: "data"
  input_file: 'names.txt'
  batch_size: 32
  num_workers: 4         # 根据你的机器核心数调整

# 训练器 (PyTorch Lightning Trainer) 配置
training:
  max_steps: 10000       # 默认训练步数
  eval_interval: 500     # 每500步进行一次验证
  # 传递给 pl.Trainer 的额外参数
  trainer_args:
    accelerator: 'auto'  # 自动检测 'cpu', 'cuda', 'mps'
    devices: 'auto'
    log_every_n_steps: 10

# 模型架构的默认参数
# 这些参数主要用于 Transformer，但为其他模型提供了默认值
model:
  type: 'transformer'    # 默认使用的模型类型
  n_layer: 4
  n_head: 4
  n_embd: 64
  n_embd2: 64            # 对于 RNN/MLP 等模型的次要嵌入维度

# 优化器配置
optimizer:
  learning_rate: 0.0005  # 5e-4
  weight_decay: 0.01