# configs/base_config.yaml

# --- Data Configuration ---
data_path: "data/poetry.json"
tokenizer_path: "data/tokenizer.pkl"
processed_data_path: "data/processed_data.pkl"
cleaner_type: "poetry"
content_field: "contents"

# --- Training Parameters ---
# 我们将在后续阶段使用这些参数
training_params:
  batch_size: 32
  # 上下文窗口大小：模型一次能看到多少个字符
  context_window: 64 

# --- PyTorch Lightning Trainer Configuration ---
trainer_params:
  max_epochs: 100
  # 如果你有GPU，可以改为1, 2, ...
  accelerator: "auto" # or "gpu"
  devices: 1