# configs/rnn.yaml
# --------------------------------------------------
# RNN (Recurrent Neural Network) 模型的特定配置。
# 支持基础RNN和GRU两种单元类型。
# 它会加载 base_config.yaml，然后用以下值覆盖默认设置。
# --------------------------------------------------

# 将输出保存到专门的目录
system:
  work_dir: 'out/rnn'

# RNN 模型的训练配置
training:
  max_steps: 8000        # RNN 需要较多步数来学习时序依赖

# RNN 模型的关键参数
model:
  type: 'rnn'
  # 词嵌入维度
  n_embd: 64             # 词嵌入向量的维度
  # RNN 隐藏状态维度
  n_embd2: 128           # RNN 隐藏状态的维度，通常比词嵌入维度大
  # RNN 单元类型：'rnn' 或 'gru'
  cell_type: 'gru'       # 默认使用GRU，因为它能更好地处理长期依赖

# RNN 模型适合中等的学习率
optimizer:
  learning_rate: 0.001   # 1e-3，适合RNN的学习率
  weight_decay: 0.01
  # RNN 训练时可能需要梯度裁剪来防止梯度爆炸
  params:
    betas: [0.9, 0.95]
    eps: 1e-8
