# configs/rnn_basic.yaml
# --------------------------------------------------
# 基础RNN模型的配置（使用vanilla RNN单元）。
# 相比GRU，基础RNN更简单但可能在长序列上表现较差。
# --------------------------------------------------

# 将输出保存到专门的目录
system:
  work_dir: 'out/rnn_basic'

# 基础RNN的训练配置
training:
  max_steps: 6000        # 基础RNN可能需要较少步数
  eval_interval: 300     # 更频繁的评估

# 基础RNN模型参数
model:
  type: 'rnn'
  # 词嵌入维度
  n_embd: 64             # 词嵌入向量的维度
  # RNN 隐藏状态维度
  n_embd2: 96            # 基础RNN使用稍小的隐藏状态维度
  # 使用基础RNN单元
  cell_type: 'rnn'       # 使用vanilla RNN单元

# 基础RNN可能需要稍低的学习率
optimizer:
  learning_rate: 0.0008  # 8e-4，比GRU稍低
  weight_decay: 0.01
  params:
    betas: [0.9, 0.95]
    eps: 1e-8
